### ISSUE TITLE
[Bug] Clicking on Spellbook error & Travel to Acherus

### ISSUE THREAD

**Issue by TasanDK** [ZelionGG/XIV_Databar-Continued#35] opened 2024-08-14 07:31 UTC
1. Greetings i am getting addon blocked action message when i click in the spellbook icons.
I get the following error from bugshack:

1x [ADDON_ACTION_FORBIDDEN] AddOn 'XIV_Databar_Continued' tried to call the protected function 'CastSpellBookItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CastSpellBookItem'
[string "@Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua"]:591: in function `OnIconClick'
[string "@Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua"]:728: in function <...rd_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua:724>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

2. Also after today's patch the Acherus travel is not working on my DK anymore.

**Comment by ZelionGG** [comment] 2024-08-20 08:33
Heya, thank you for the report, I was on vacation for the last 3 weeks ! I'll investigate this issue today.

**Comment by ZelionGG** [comment] 2024-08-26 16:10
Heya, Acherus teleport shouldn't throw errors anymore with v3.0.3, let me know if that's the case ! 

For the Spellbook error, I can't reproduce it for now, let me know if you have more context on this error please.

Thank you again.

**Comment by TasanDK** [comment] 2024-08-26 21:22
> Heya, Acherus teleport shouldn't throw errors anymore with v3.0.3, let me know if that's the case !
> 
> For the Spellbook error, I can't reproduce it for now, let me know if you have more context on this error please.
> 
> Thank you again.

Hm it seems that still is not working. When i click it it forces teleport to dalaran and if i reload ui it gets greyed out and unusable.

**Comment by ZelionGG** [comment] 2024-08-27 23:17
Heya, thank you for the feedback, I pushed a fix that will get released ASAP !

**Comment by ZelionGG** [comment] 2024-09-02 22:44
Heya, after such a long wait, version 3.1 is out and should fix that issue !

Let me know if you still have a problem !

Thank you again for the feedback and for helping me maintain XIV Databar Continued and enjoy !

**Closed** 2024-09-13 09:06 UTC
Labels: investigation required, retail
