### ISSUE TITLE
[Bug] Underscore Throwaway Value from other addons is being treated as an Input

### ISSUE THREAD

**Issue by RealoFoxtrot** [ZelionGG/XIV_Databar-Continued#41] opened 2024-09-01 20:00 UTC
**Describe the bug**
The short description:
I have found that XIV is causing _ to be treated as an input instead of a throwaway value.
At least this has happened when using the command SendChatMessage, with _ being used to ignore the language input

**To Reproduce**
1. Load the game wiht XIV databar working
2. type `/script SendChatMessage("Test","SAY",_,_)`
3. View message "You Cannot Speak That Language"

**Expected behavior**
What should happen is _ should be treated as a throwaway character and ignored, sending the message anyhow.

**Lua error logs**
No LUA error

**Screenshots**

**WoW Version (please complete the following information)**
 - WoW Flavour: Retail
 - Version 11.0.2 (56421)

**XIV_Databar Continued Version**
Which version of XIV_Databar Continued are you using ?
3.0.3

**Additional context**
I am sure this is XIV as I have disabled all addons except XIV and then turned it off and it is definitely XIV that is causing this behavior.
I have no clue what could be causing it though.
However, the solution for addon/Scripters is to use nil instead of _

**Comment by ZelionGG** [comment] 2024-09-01 21:49
Heya, interesting feedback, I identified the bug and that is caused by variables reassignments like
`self.cook.name, self.cook.defIcon, self.cook.lvl, self.cook.maxLvl, _, _, self.cook.id, _ = GetProfessionInfo(self.cook.idx)`

It is happening in multiple modules, I identified all of the faulty reassignments and this should be fixed in the next release !

Thank you for letting me know about that strange interaction !

**Comment by ZelionGG** [comment] 2024-09-02 22:34
Heya, after such a long wait, version 3.1 is out and should fix that issue ! 

Let me know if you still have a problem !

Thank you again for the feedback and for helping me maintain XIV Databar Continued and enjoy !

**Comment by RealoFoxtrot** [comment] 2024-09-04 23:48
Seems like it's fixed it!

**Comment by ZelionGG** [comment] 2024-09-05 12:42
Sweet, thank you again for the report and enjoy !

**Closed by ZelionGG** 2024-09-05 12:42 UTC
Labels: bug, in progress
