### ISSUE TITLE
[Bug] :HookScript is not allowed on LibQTip tooltips

### ISSUE THREAD

**Issue by Nightshadow-hub** [ZelionGG/XIV_Databar-Continued#39] opened 2024-08-26 21:17 UTC
Hovering over the spec talent choice and social consistently produces the following lua error. Tried deleting and redownloading the addon and error persists:

Message: :HookScript is not allowed on LibQTip tooltips
Time: Mon Aug 26 16:13:11 2024
Count: 1
Stack: :HookScript is not allowed on LibQTip tooltips
[string "@Interface/AddOns/XIV_Databar_Continued/Mainline/modules/talent.lua"]:829: in function `ShowTooltip'
[string "@Interface/AddOns/XIV_Databar_Continued/Mainline/modules/talent.lua"]:398: in function <...ns/XIV_Databar_Continued/Mainline/modules/talent.lua:391>

Locals: self = <table> {
 modules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 talentFrame = talentFrame {
 }
 specOptionString = FontString {
 }
 currentSpecID = 1
 specCoords = <table> {
 }
 defaultModuleState = true
 extraPadding = 30
 enabledState = true
 loadoutName = ""
 useElvUI = true
 specFrame = Button {
 }
 defaultModuleLibraries = <table> {
 }
 name = "XIV_Databar_Continued_TalentModule"
 currentLootSpecID = 577
 orderedModules = <table> {
 }
 lootSpecButtons = <table> {
 }
 LTip = <table> {
 }
 lootSpecPopup = LootPopup {
 }
 specPopup = SpecPopup {
 }
 specText = FontString {
 }
 specIcon = Texture {
 }
 optionTextExtra = 4
 classIcon = "Interface\AddOns\XIV_Databar_Continued\media\spec\DEMONHUNTER"
 lootSpecOptionString = FontString {
 }
 loadoutButtons = <table> {
 }
 specButtons = <table> {
 }
 moduleName = "TalentModule"
}
tooltip = Frame {
 key = "TalentTooltip"
 template = "Transparent"
 scrollChild = Frame {
 }
 cell_margin_h = 6
 labelProvider = <table> {
 }
 height = 88.666674
 regularFont = GameTooltipText {
 }
 layoutType = "TooltipDefaultLayout"
 headerFont = GameTooltipHeaderText {
 }
 scrollFrame = ScrollFrame {
 }
 NineSlice = Frame {
 }
 colspans = <table> {
 }
 width = 272.666695
 lines = <table> {
 }
 cell_margin_v = 3
 columns = <table> {
 }
}
r = 0.639216
g = 0.188235
b = 0.788235
_ = 577
name = "Havoc"
xb = <table> {
 defaults = <table> {
 }
 modules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 fontFlags = <table> {
 }
 defaultModuleState = true
 frames = <table> {
 }
 miniTextPosition = "BOTTOM"
 db = <table> {
 }
 enabledState = true
 Changelog = <table> {
 }
 name = "XIV_Databar_Continued"
 orderedModules = <table> {
 }
 LSM = <table> {
 }
 constants = <table> {
 }
 timerRefresh = true
 defaultModuleLibraries = <table> {
 }
 L = <table> {
 }
}
L = <table> {
 Show XP Bar Below Max Level = "Show XP Bar Below Max Level"
 Right = "Right"
 Second Currency = "Second Currency"
 Cleaned = "Cleaned"
 Currency Select = "Currency Select"
 Enable Loadout Switcher = "Enable Loadout Switcher"
 Left-Click = "Left-Click"
 Bottom = "Bottom"
 Whisper BNet = "Whisper BNet"
 Show Pets Button = "Show Pets Button"
 Use Server Time = "Use Server Time"
 Hide Event Text = "Hide Event Text"
 Addons to Show in Tooltip = "Addons to Show in Tooltip"
 Open Artifact = "Open Artifact"
 Hide order hall bar = "Hide order hall bar"
 Hide BNet App Friends = "Hide BNet App Friends"
 Show Character Button = "Show Character Button"
 Local Time = "Local Time"
 Master Volume = "Master Volume"
 Whisper Character = "Whisper Character"
 Ready = "Ready"
 Hide Bar in combat = "Hide Bar in combat"
 Durability Warning Threshold = "Durability Warning Threshold"
 Use Class Colors for XP Bar = "Use Class Colors for XP Bar"
 Bar Position = "Bar Position"
 Use Class Color for Text = "Use Class Color for Text"
 Module Spacing = "Module Spacing"
 Show Chat Button = "Show Chat Button"
 Empty Hearthstones List = "If you see an empty list, /reload your UI a few seconds after the initial loading (Blizzard is loading items informations asynchronously so that's the only solution for now)."
 Modifier for friend invite = "Modifier for friend invite"
 Changelog = "Changelog"
 Bar Color = "Bar Color"
 Icon Spacing = "Icon Spacing"
 %month%-%day%-%year% = "%month%-%day%-%year%"
 Port Options = "Port Options"
 Social Text Offset = "Social Text Offset"
 Hover = "Hover"
 Current Specialization = "Current Specialization"
 Toggle Profession Spellbook = "Toggle Profession Spellbook"
 Travel = "Travel"
 Show Talents Button = "Show Talen

**Comment by ZHumphries** [comment] 2024-08-30 09:30
I am also seeing exactly the same error

**Comment by ZelionGG** [comment] 2024-08-30 13:59
Hello, might be a duplicate of #23, closing this one and keeping the other one to track this error.

**Closed by ZelionGG** 2024-08-30 13:59 UTC
