### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by srtzero** [ZelionGG/XIV_Databar-Continued#4] opened 2023-05-13 00:34 UTC
Hello. I keep getting the below Lua error from bugsack. Seems like an issue with displaying the clock, but the clock does show.
This is for retail version 10.1.0

44x Interface\FrameXML\Bindings.xml:1 XIV_Databar_Continued/Mainline/modules/load_modules.xml:4 Error loading XIV_Databar_Continued/clock.lua

Also one quick suggestion: All other modules have the option of being enabled or disabled. It would be nice to have the same option with the clock.  Thank you.

**Comment by Vilogity** [comment] 2023-06-03 07:32
I get the same LUA ERROR

**Comment by ZelionGG** [comment] 2023-06-04 09:23
Hi, I'm gonna check if I can reproduce and try to fix it. Thanks for the feedback.

**Comment by Vilogity** [comment] 2023-06-04 15:31
Hi
I use the German client, idk if this is a different ?
And many thx for your updates, this is one of the usefull addon's out there.
If you need some to test a change you made, to fix the Error......tell me.

**Comment by ZelionGG** [comment] 2023-06-04 18:13
The bug has been reproduced and will be fixed in the coming release.

Thank you again for the reports and enjoy using XIV Continued 😄 

Don't hesitate to report if the issue is fixed on your side or if it persists for some reason.

**Closed** 2023-06-06 21:33 UTC
Labels: bug
